spring:
  application:
    name: blog_system

  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.144.128:3306/blog?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_general_ci

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    show-sql: true

  redis:
    host: 192.168.144.128
    port: 6379
    password: root

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

blog:
  system:
    image:
      # 图片本地保存路径
      dir-path: /home/manpok/docker/images/
      # 图片大小限制，单位b，大小2M
      max-size: 2097152
      # 读取图片缓冲区带
      input-stream:
        buffer: 8192
      # multi-avatar地址
      multi-avatar-url: https://api.multiavatar.com/{1}.png?apikey={2}
      # multi-avatar-api-key
      multi-avatar-api-key: t3JID2jWxkVU5X
    # solr地址
    solr:
      path: http://192.168.144.128:8983/solr/ik_core
    #swagger开关
    swagger:
      enable: false

