spring:
  application:
    name: blog_system

  datasource:
    username: root
    password: password
    url: jdbc:mysql://mysql:3306/blog_system?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_general_ci

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    show-sql: false

  redis:
    host: redis
    port: 6379
    password: password

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

blog:
  system:
    image:
      # 图片本地保存路径
      dir-path: /usr/src/myapp/images
      #存多一份给nginx用
      dir-path-nginx: /usr/src/myapp/images_nginx
      # 图片大小限制，单位b，大小2M
      max-size: 2097152
      # 读取图片缓冲区带
      input-stream:
        buffer: 8192
      # multi-avatar地址
      multi-avatar-url: https://api.multiavatar.com/{1}.png?apikey={2}
      # multi-avatar-api-key
      multi-avatar-api-key: XXXX
      # 图片重定向地址
      redirect-base-url: https://static.manpok.top/image/
      # 水印相关
      watermark:
        # 原始图片水印地址
        originFilePath: /usr/src/myapp/images/watermark.png
        # 临时图片水印地址
        tempFilePath: /usr/src/myapp/images
        # 临时图片水印文件名
        tempFileName: temp_watermark_
        # 文字水印字号
        font-size: 20
        # 文字水印文本
        text: 卧卷@ manpok
    # solr地址
    solr:
      path: http://solr:8983/solr/blog_system_search_core
    #swagger开关
    swagger:
      enable: false
    jwt-secret: XXXX
