spring:
  application:
    name: blog_system

  datasource:
    username: root
    password: root
    url: jdbc:mysql://mysql:3306/blog_system?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_general_ci

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    show-sql: false

  data:
    redis:
      host: redis
      port: 6379
      password: password

  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 50MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  threads:
    virtual:
      enabled: true

blog:
  system:
    image:
      # 图片本地保存路径
      dir-path: /usr/src/myapp/images
      #存多一份给nginx用
      dir-path-nginx: /usr/src/myapp/images_nginx
      # 图片大小限制，单位b，大小6M
      max-size: 6291456
      # 读取图片缓冲区带
      input-stream:
        buffer: 8192
      # multi-avatar地址
      multi-avatar-url: https://api.multiavatar.com/{1}.png?apikey={2}
      # multi-avatar-api-key
      multi-avatar-api-key: XXXX
      # 图片重定向地址
      redirect-base-url: http://test.static.manpok.top/image/
      # 水印相关
      watermark:
        # 原始图片水印地址
        originFilePath: /usr/src/myapp/images/watermark.png
        # 临时图片水印地址
        tempFilePath: /usr/src/myapp/images
        # 临时图片水印文件名
        tempWatermarkFileName: temp_watermark_
        #临时图片PNG
        tempPNGFileName: temp_PNG_
        # 文字水印字号
        font-size: 20
        # 文字水印文本
        text: 卧卷@ manpok
      max-width-height: 1440
      webp:
        shell-name:
          /bin/bash
        shell-param:
          -c
    # solr地址
    solr:
      path: http://solr:8983/solr/blog_system_search_core
    audio:
      # 存放临时音频文件的地址
      temp-dir-path: /usr/src/myapp/audios/
    jwt-secret: XXXX

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
